// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKTCc4TYQYz2PhHyHsFdrYEcgfm5EGI-E',
    appId: '1:250392337840:web:4b2ee89185394aa4c18a75',
    messagingSenderId: '250392337840',
    projectId: 'quicklogi',
    authDomain: 'quicklogi.firebaseapp.com',
    databaseURL: 'https://quicklogi-default-rtdb.firebaseio.com',
    storageBucket: 'quicklogi.appspot.com',
    measurementId: 'G-6Z51BDE4GS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHcBtR0KquTLR3huXWRRMQNBGx3F0duXw',
    appId: '1:250392337840:android:94b5a9450a9b809ec18a75',
    messagingSenderId: '250392337840',
    projectId: 'quicklogi',
    databaseURL: 'https://quicklogi-default-rtdb.firebaseio.com',
    storageBucket: 'quicklogi.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCHMuRKgZNSuq0bW3vmGr13jlp7XTF4IE',
    appId: '1:250392337840:ios:5f17193ad159d308c18a75',
    messagingSenderId: '250392337840',
    projectId: 'quicklogi',
    databaseURL: 'https://quicklogi-default-rtdb.firebaseio.com',
    storageBucket: 'quicklogi.appspot.com',
    iosClientId: '250392337840-tgjf0fdr84k4ncms5mj13t2qi6ini007.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCHMuRKgZNSuq0bW3vmGr13jlp7XTF4IE',
    appId: '1:250392337840:ios:5f17193ad159d308c18a75',
    messagingSenderId: '250392337840',
    projectId: 'quicklogi',
    databaseURL: 'https://quicklogi-default-rtdb.firebaseio.com',
    storageBucket: 'quicklogi.appspot.com',
    iosClientId: '250392337840-tgjf0fdr84k4ncms5mj13t2qi6ini007.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
